os: linux
dist: xenial
language: node_js
node_js:
  - "16"
notifications:
  email: true
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: build
  on:
    branch: master
